exercises/djangomusic/music/history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),

##########
# ARTIST PATHS
    path('artists/', views.ArtistListView.as_view(), name='artists'),
    path('artists/<int:pk>/', views.ArtistDetailView.as_view(), name='artist_detail'),
    path('artists/add/', views.ArtistFormView.as_view(), name='artist_form'),

##########
# ALBUM PATHS
    path('albums/', views.AlbumListView.as_view(), name='albums'),
    path('albums/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('albums/add/', views.AlbumFormView.as_view(), name='album_form'),

##########
# SONG PATHS
    path('songs/', views.SongListView.as_view(), name='song_list'),
    path('songs/<int:pk>/', views.SongDetailView.as_view(), name='song_detail'),
    path('songs/add/', views.SongFormView.as_view(), name='song_form'),

##########
#  GENRE PATHS
    path('genres/', views.GenreListView.as_view(), name='genre_list'),
    path('genres/<int:pk>/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('genres/add/', views.GenreFormView.as_view(), name='genre_form'),
]

exercises/djangomusic/music/music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls'))
]

exercises/djangomusic/music/history/models.py
# import datetime
from django.db import models
from django.utils import timezone


# Artist Model
class Artist(models.Model):
    artist_name = models.CharField(default="", max_length=200)
    # pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.artist_name

#  Album Model
class Album(models.Model):
    title = models.CharField(default="", max_length=200)
    album_date = models.DateField(auto_now=False, auto_now_add=False)
    label = models.CharField(default="", max_length=30)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return "{0}".format(self.title)

# Genre Modle
class Genre(models.Model):
    style = models.CharField(default="", max_length=30)

    def __str__(self):
        return "{0}".format(self.style)

# Genre Songs
class Songs(models.Model):
    title = models.CharField(default="", max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return "{0}".format(self.title)

exercises/djangomusic/music/history/forms.py
from django import forms
from .models import Artist, Album, Genre, Songs


# FORMS are used for USER input to add information to the Database
class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['artist_name']

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'label', 'album_date']

class SongForm(forms.ModelForm):
    class Meta:
        model = Songs
        fields = ['title',]

class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['style',]

exercises/djangomusic/music/history/views.py
# from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
# from django.template import loader
from django.views.generic import ListView, FormView, DetailView, CreateView, TemplateView
from .models import Artist, Songs, Album, Genre
from .forms import ArtistForm, AlbumForm, SongForm, GenreForm

class IndexView(TemplateView):
    template_name = 'history/index.html'

    def location(self):
        return 'home'

# ===============================
# ARTIST Views
class ArtistListView(ListView):
    model = Artist
    context_object_name = 'artist_list' #this allows you to change object_list into a readable and easy to access variable from templates

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "artists"
        return context # A Context is a dictionary with variable names as the "key" and their values as the "value"

class ArtistFormView(FormView):
    template_name = 'history/artist_form.html'
    form_class = ArtistForm
    success_url = '/history/artists/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "artists"
        return context

    def form_valid(self, form):
        form.save()
        return super(ArtistFormView, self).form_valid(form)

class ArtistDetailView(DetailView):
    model = Artist


# ===============================
# ALBUM Views
class AlbumListView(ListView):
    model = Album
    context_object_name = 'album_list' #this allows you to change object_list into a readable and easy to access variable from templates

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "albums"
        return context # A Context is a dictionary with variable names as the "key" and their values as the "value"

class AlbumFormView(FormView):
    template_name = 'history/album_form.html'
    form_class = AlbumForm
    success_url = '/history/albums/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "albums"
        return context

    def form_valid(self, form):
        form.save()
        return super(AlbumFormView, self).form_valid(form)

class AlbumDetailView(DetailView):
    model = Album


# ===============================
# SONG Views
class SongListView(ListView):
    model = Songs
    context_object_name = 'song_list' #this allows you to change object_list into a readable and easy to access variable from templates

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "songs"
        return context # A Context is a dictionary with variable names as the "key" and their values as the "value"


class SongFormView(FormView):
    template_name = 'history/song_form.html'
    form_class = SongForm
    success_url = '/history/songs/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "songs"
        return context

    def form_valid(self, form):
        form.save()
        return super(SongFormView, self).form_valid(form)


class SongDetailView(DetailView):
    model = Songs


# ===============================
# GENRE Views
class GenreListView(ListView):
    model = Genre
    context_object_name = 'genre_list' #this allows you to change object_list into a readable and easy to access variable from templates

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "genres"
        return context # A Context is a dictionary with variable names as the "key" and their values as the "value"


class GenreFormView(FormView):
    template_name = 'history/genre_form.html'
    form_class = GenreForm
    success_url = '/history/genres/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "genres"
        return context

    def form_valid(self, form):
        form.save()
        return super(GenreFormView, self).form_valid(form)


class GenreDetailView(DetailView):
    model = Genre

exercises/djangomusic/music/history/templates/history/album_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'history/album.css' %}" />

<h1>These are songs from {{album.title}}</h1>

<h2>by {{album.artist}}</h2>


{% comment %} <h2>Some other albums {{artist.artist_name}} is known for</h2> {% endcomment %}
<ul>
  {% comment %} loop over the artist's associated albums. So cool! {% endcomment %}
  {% for song in album.song_list.all %}
    <li>
      <a href="{% url 'history:song_detail' song.id %}">{{song.title}}</a>
    </li>
  {% endfor %}
</ul>
{% comment %} Button that lets you add the remaining songs to the album {% endcomment %}
<form action="/history/songs/add" method='get'>
    <input type="submit" value="Add Songs">
  </form>
{% comment %} Button that takes you back home {% endcomment %}
<form action="/history/" method='get'>
  <input type="submit" value="Home">
</form>

exercises/djangomusic/music/history/templates/history/album_form.html
<h3>Add a new album to your collection</h3>

<form method='post'>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Save Album">
</form>

exercises/djangomusic/music/history/templates/history/album_list.html
{% extends "history/index.html" %}

{% block main_stuff %}

  {% include "history/nav_bar.html" with nav_location=location %}

  <h1>These Are Albums from AlbumListView </h1>

  <ul>
    {% for album in album_list %}
    <li>
      <a href="{% url 'history:album_detail' album.id %}">{{album.title}} by {{album.artist_id}}</a>
    </li>
    {% endfor %}
  </ul>
{% endblock main_stuff %}

<!-- Decoupling is involved with 'history:artist_detail' -->

exercises/djangomusic/music/history/templates/history/albums.html
{% extends "index.html" %}

{% block main_stuff %}
  <h1>These Are Albums from AlbumListTemplateView </h1>

  <ul>
    {% for album in view.album_list %}
      <li>
        <a href="{% url 'history:album_detail' album.id %}">{{album.title}}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock main_stuff %}

exercises/djangomusic/music/history/templates/history/artist_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'history/artist.css' %}" />

<h1>This is an Artist and some Albums They Recorded</h1>

<h2>{{artist.artist_name}}</h2>


<h2>Some other albums {{artist.artist_name}} is known for</h2>
<ul>
  {% comment %} loop over the artist's associated albums. So cool! {% endcomment %} {% for album in artist.album_set.all %}
  <li>
    {{album.title}} released by {{album.label}}.
  </li>
  {% endfor %}
</ul>

<form action="/history/albums/add" method='get'>
  <input type="submit" value="Add An Album">
</form>

{% comment %} Button that takes you back home {% endcomment %}
<form action="/history/" method='get'>
  <input type="submit" value="Home">
</form>

exercises/djangomusic/music/history/templates/history/artist_form.html
<h3>Add a new artist to your collection</h3>

<form method='post'>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Save Artist">
</form>

exercises/djangomusic/music/history/templates/history/artist_list.html
{% extends "history/index.html" %}

{% block main_stuff %}

  {% include "history/nav_bar.html" with nav_location=location %}

  <h1>These Are Made Up of Artists from ArtistListView </h1>

  <ul>
    {% for artist in artist_list %}
    <li>
      <a href="{% url 'history:artist_detail' artist.id %}">{{artist.artist_name}}</a>
    </li>
    {% endfor %}
  </ul>

  <form action="/history/artists/add" method='get'>
    <input type="submit" value="Add An Artist">
  </form>

{% endblock main_stuff %}



<!-- Decoupling is involved with 'history:artist_detail' -->

exercises/djangomusic/music/history/templates/history/artists.html
{% extends "index.html" %}

{% block main_stuff %}
  <h1>These Are Made Up Artists from ArtistListTemplateView </h1>

  <ul>
    {% for artist in view.artist_list %}
      <li>
        <a href="{% url 'history:artist_detail' artist.id %}">{{artist.artist_name}}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock main_stuff %}

exercises/djangomusic/music/history/templates/history/genres.html
{% extends "index.html" %}

{% block main_stuff %}
  <h1>These Are Genres from ArtistListTemplateView </h1>

  <ul>
    {% for genre in view.genre_list %}
      <li>
        <a href="{% url 'history:genre_detail' genre.id %}">{{genre.style}}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock main_stuff %}

exercises/djangomusic/music/history/templates/history/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'history/style.css' %}" />

<h1>Welcome to My Music Collection</h1>

{% block main_stuff %}
  {% comment %} Including nav_bar in each template so we can pass the location to it each time {% endcomment %}
  {% include "history/nav_bar.html" with nav_location=view.location %}
  {% comment %} <img src="{% static 'history/images/jronk.gif' %}" alt="jronk"> {% endcomment %}
{% endblock main_stuff %}

exercises/djangomusic/music/history/templates/history/songs.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'history/songs.css' %}" />

{% extends "index.html" %}

{% block main_stuff %}
  <h1>These Are Songs from SongListTemplateView </h1>

  <ul>
    {% for song in view.song_list %}
      <li>
        <a href="{% url 'history:song_detail' song.id %}">{{song.title}}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock main_stuff %}

exercises/djangomusic/music/history/templates/history/songs_detail.html
{% comment %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'history/artist.css' %}" /> {% endcomment %}

<h1>These are Songs by {{songs.artist}}</h1>

<h2>from the album "{{songs.album}}"</h2>

<ul>
  {% comment %} loop over the artist's associated albums. So cool! {% endcomment %} {% for song in song_list %}
  <li>
    {{songs.title}} -- {{songs.genre}}
  </li>
  {% endfor %}
</ul>

<form action="/history/songs/add" method='get'>
  <input type="submit" value="Add A song">
</form>

{% comment %} Button that takes you back home {% endcomment %}
<form action="/history/" method='get'>
  <input type="submit" value="Home">
</form>

exercises/djangomusic/music/history/templates/history/songs_form.html
<h3>Add a new song to your collection</h3>

<form method='post'>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Save Song">
</form>

exercises/djangomusic/music/history/templates/history/songs_list.html
{% extends "history/index.html" %}

{% block main_stuff %}

  {% include "history/nav_bar.html" with nav_location=location %}

  <h1>These Are Songs From SongListView </h1>

  <ul>
    {% for song in song_list %}
    <li>
      <a href="{% url 'history:song_detail' song.id %}">{{song.title}}</a>
    </li>
    {% endfor %}
  </ul>

  <form action="/history/songs/add" method='get'>
    <input type="submit" value="Add A Song">
  </form>

{% endblock main_stuff %}



<!-- Decoupling is involved with 'history:artist_detail' -->